-- 카테고리 별 도서 판매량 집계하기
SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01%'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY ASC;
