# 둘째 자리에서 반올림 -> 첫째 자리로 나타남

SELECT ROUTE, 
       CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, 
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE 
GROUP BY ROUTE 
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC ;